from turtle import*
from random import*
speed('fastest')
color('skyblue')
dot(500)
# 画身体
penup() 
goto(0,-260) 
color('yellow') 
pendown() 
begin_fill() 
circle(100,360,5) 
end_fill()
penup()
#画耳朵
goto(-100,-40) 
color('coral') 
pendown() 
begin_fill()  
circle(20) 
end_fill() 
penup() 
goto(100,-40) 
color('coral') 
pendown() 
begin_fill() 
circle(20) 
end_fill() 
penup()
#画脸 
goto(0,-100) 
color('coral') 
pendown() 
begin_fill()  
circle(100,360,8) 
end_fill() 
penup()
# 画头发
for i in range(50):
    goto(randint(-100,100),randint(0,100))
    color('brown')
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup() 
# 画眼睛
goto(-50,-30)
color('black')
pendown() 
begin_fill() 
circle(20)
end_fill() 
penup() 
goto(50,-30) 
color('black') 
pendown() 
begin_fill()  
circle(20) 
end_fill() 
penup() 
#画嘴 
goto(-20,-70) 
color('red') 
pendown() 
forward(50) 
penup()
# 签名字
goto(180,-260)
write('可多的作品',font= [' 黑体 ',20,'normal'])
hideturtle()
