from random import *
import time
#用随机数生成一个4位数的验证码
a = randint(1000,9999)
print("验证码是：",a)
answer = input("请输入验证码：")
answer = int(answer)
#用输入的验证码与系统生成的比对，输入正确表示验证通过~
if a == answer:
    print("登录中···")
    time.sleep(0.5)
    print("  0%[==========]")
    time.sleep(0.5)
    print(" 10%[+=========]")
    time.sleep(0.5)
    print(" 20%[++========]")
    time.sleep(0.5)
    print(" 30%[+++=======]")
    time.sleep(0.5)
    print(" 40%[++++======]")
    time.sleep(0.5)
    print(" 50%[+++++=====]")
    time.sleep(0.5)
    print(" 60%[++++++====]")
    time.sleep(0.5)
    print(" 70%[+++++++===]")
    time.sleep(0.5)
    print(" 80%[++++++++==]")
    time.sleep(0.5)
    print(" 90%[+++++++++=]")
    time.sleep(0.5)
    print("100%[++++++++++]")
    time.sleep(2)
    print("登录成功！！！")
else:
    print("登录中···")
    time.sleep(0.5)
    print("  0%[==========]")
    time.sleep(0.5)
    print(" 10%[+=========]")
    time.sleep(2)
    print("检测到验证码不正确，")
    time.sleep(0.1)
    print("登录失败！！！")